In [1]:
import pickle
from train import mydist
import pandas as pd
import numpy as np

In [2]:
with open('model_knn.pkl', 'rb') as f:
    model = pickle.load(f)
    f.close()

In [3]:
# # Test Cells
# HP = 241
# TORQUE = 273
# TURBO = 1
# SUPER = 0
# TWO_DOOR = 0
# MAN = 1
# AUTO = 1
# FWD = 1
# RWD = 0
# AWD = 0

# similar_cars = model.kneighbors([[HP,TORQUE,TURBO,SUPER,TWO_DOOR,MAN,AUTO,FWD,RWD,AWD]])[1][0]
# print(similar_cars)

In [14]:
df = pd.read_csv('data/train_data.csv')

In [18]:
sim_cars = {}
for idx, car in df[['hp', 'torque', 'turbo', 'super', 'two_door', 'man', 'auto', 'fwd', 'rwd', 'awd']].iterrows():
    similar_cars = model.kneighbors([car.values])[1][0]
    sim_car_id = []
    for i in similar_cars[1:4]:
        sim_car_id.append(df.iloc[i].id)
    sim_cars[df.iloc[idx].id] = sim_car_id
    print(similar_cars)

[ 0 98 97 53 58]
[ 1  3 55  2 33]
[ 2 49  4  5  1]
[ 3 55 73  1 59]
[ 4  5  2 80 87]
[ 5  4  2 80 87]
[ 6 17 79 87 80]
[  7  26   8 111  10]
[  8 111  41  40   7]
[ 9 61 26 10 18]
[10  9 26  7 40]
[ 11  12 106  44 108]
[ 11  12 106  44 108]
[ 13 103 104  96  66]
[ 14  39 109  69  86]
[15 20 21 31 14]
[16 82 71 54 57]
[17  6 79 80 87]
[ 18  22  23  61 102]
[19 76 42 24 25]
[ 20  21  15 114  39]
[ 20  21  15 114  39]
[ 23  22  18 102  61]
[ 23  22  18 102  61]
[25 24 76 19 42]
[25 24 76 19 42]
[26  7 61 18  9]
[ 27  29 113  65  48]
[28 90 69 30 68]
[ 29  27  78  65 113]
[ 30  90  28 112 109]
[ 31 112  45  69 109]
[32 95 56 51 52]
[33  1  0 98 32]
[ 34 110  96 104 103]
[ 35  86  68  72 109]
[36 37 62 50 81]
[37 62 50 36 81]
[ 38  74  63 115 111]
[39 14 77 76 24]
[40 41 75 74  8]
[41 40 75  8 74]
[42 43 76 19 24]
[42 43 76 19 25]
[44 67 85 84 12]
[ 45  92  31 112  48]
[46 47 83 89 64]
[46 47 83 89 64]
[ 48 114 113  92  27]
[49  2  4 57 87]
[50 37 36 62 81]
[51 93 95 32 52]
[52 56 95 53 97]

In [19]:
sim_cars

{1: [99, 98, 54],
 2: [4, 56, 3],
 3: [50, 5, 6],
 4: [56, 74, 2],
 5: [6, 3, 81],
 6: [5, 3, 81],
 7: [18, 80, 88],
 8: [27, 9, 112],
 9: [112, 42, 41],
 10: [62, 27, 11],
 11: [10, 27, 8],
 12: [13, 107, 45],
 13: [13, 107, 45],
 14: [104, 105, 97],
 15: [40, 110, 70],
 16: [21, 22, 32],
 17: [83, 72, 55],
 18: [7, 80, 81],
 19: [23, 24, 62],
 20: [77, 43, 25],
 21: [22, 16, 115],
 22: [22, 16, 115],
 23: [23, 19, 103],
 24: [23, 19, 103],
 25: [25, 77, 20],
 26: [25, 77, 20],
 27: [8, 62, 19],
 28: [30, 114, 66],
 29: [91, 70, 31],
 30: [28, 79, 66],
 31: [91, 29, 113],
 32: [113, 46, 70],
 33: [96, 57, 52],
 34: [2, 1, 99],
 35: [111, 97, 105],
 36: [87, 69, 73],
 37: [38, 63, 51],
 38: [63, 51, 37],
 39: [75, 64, 116],
 40: [15, 78, 77],
 41: [42, 76, 75],
 42: [41, 76, 9],
 43: [44, 77, 20],
 44: [44, 77, 20],
 45: [68, 86, 85],
 46: [93, 32, 113],
 47: [48, 84, 90],
 48: [48, 84, 90],
 49: [115, 114, 93],
 50: [3, 5, 58],
 51: [38, 37, 63],
 52: [94, 96, 33],
 53: [57, 96, 54],


In [20]:
### Test

In [25]:
with open('sim_cars.pkl', 'rb') as test:
    dic = pickle.load(test)

In [27]:
dic

{1: [99, 98, 54],
 2: [4, 56, 3],
 3: [50, 5, 6],
 4: [56, 74, 2],
 5: [6, 3, 81],
 6: [5, 3, 81],
 7: [18, 80, 88],
 8: [27, 9, 112],
 9: [112, 42, 41],
 10: [62, 27, 11],
 11: [10, 27, 8],
 12: [13, 107, 45],
 13: [13, 107, 45],
 14: [104, 105, 97],
 15: [40, 110, 70],
 16: [21, 22, 32],
 17: [83, 72, 55],
 18: [7, 80, 81],
 19: [23, 24, 62],
 20: [77, 43, 25],
 21: [22, 16, 115],
 22: [22, 16, 115],
 23: [23, 19, 103],
 24: [23, 19, 103],
 25: [25, 77, 20],
 26: [25, 77, 20],
 27: [8, 62, 19],
 28: [30, 114, 66],
 29: [91, 70, 31],
 30: [28, 79, 66],
 31: [91, 29, 113],
 32: [113, 46, 70],
 33: [96, 57, 52],
 34: [2, 1, 99],
 35: [111, 97, 105],
 36: [87, 69, 73],
 37: [38, 63, 51],
 38: [63, 51, 37],
 39: [75, 64, 116],
 40: [15, 78, 77],
 41: [42, 76, 75],
 42: [41, 76, 9],
 43: [44, 77, 20],
 44: [44, 77, 20],
 45: [68, 86, 85],
 46: [93, 32, 113],
 47: [48, 84, 90],
 48: [48, 84, 90],
 49: [115, 114, 93],
 50: [3, 5, 58],
 51: [38, 37, 63],
 52: [94, 96, 33],
 53: [57, 96, 54],


In [29]:
list(dic.items())

[(1, [99, 98, 54]),
 (2, [4, 56, 3]),
 (3, [50, 5, 6]),
 (4, [56, 74, 2]),
 (5, [6, 3, 81]),
 (6, [5, 3, 81]),
 (7, [18, 80, 88]),
 (8, [27, 9, 112]),
 (9, [112, 42, 41]),
 (10, [62, 27, 11]),
 (11, [10, 27, 8]),
 (12, [13, 107, 45]),
 (13, [13, 107, 45]),
 (14, [104, 105, 97]),
 (15, [40, 110, 70]),
 (16, [21, 22, 32]),
 (17, [83, 72, 55]),
 (18, [7, 80, 81]),
 (19, [23, 24, 62]),
 (20, [77, 43, 25]),
 (21, [22, 16, 115]),
 (22, [22, 16, 115]),
 (23, [23, 19, 103]),
 (24, [23, 19, 103]),
 (25, [25, 77, 20]),
 (26, [25, 77, 20]),
 (27, [8, 62, 19]),
 (28, [30, 114, 66]),
 (29, [91, 70, 31]),
 (30, [28, 79, 66]),
 (31, [91, 29, 113]),
 (32, [113, 46, 70]),
 (33, [96, 57, 52]),
 (34, [2, 1, 99]),
 (35, [111, 97, 105]),
 (36, [87, 69, 73]),
 (37, [38, 63, 51]),
 (38, [63, 51, 37]),
 (39, [75, 64, 116]),
 (40, [15, 78, 77]),
 (41, [42, 76, 75]),
 (42, [41, 76, 9]),
 (43, [44, 77, 20]),
 (44, [44, 77, 20]),
 (45, [68, 86, 85]),
 (46, [93, 32, 113]),
 (47, [48, 84, 90]),
 (48, [48, 84, 90]),

In [30]:
for id, sim_ids in list(dic.items()):
    print(sim_ids)

[99, 98, 54]
[4, 56, 3]
[50, 5, 6]
[56, 74, 2]
[6, 3, 81]
[5, 3, 81]
[18, 80, 88]
[27, 9, 112]
[112, 42, 41]
[62, 27, 11]
[10, 27, 8]
[13, 107, 45]
[13, 107, 45]
[104, 105, 97]
[40, 110, 70]
[21, 22, 32]
[83, 72, 55]
[7, 80, 81]
[23, 24, 62]
[77, 43, 25]
[22, 16, 115]
[22, 16, 115]
[23, 19, 103]
[23, 19, 103]
[25, 77, 20]
[25, 77, 20]
[8, 62, 19]
[30, 114, 66]
[91, 70, 31]
[28, 79, 66]
[91, 29, 113]
[113, 46, 70]
[96, 57, 52]
[2, 1, 99]
[111, 97, 105]
[87, 69, 73]
[38, 63, 51]
[63, 51, 37]
[75, 64, 116]
[15, 78, 77]
[42, 76, 75]
[41, 76, 9]
[44, 77, 20]
[44, 77, 20]
[68, 86, 85]
[93, 32, 113]
[48, 84, 90]
[48, 84, 90]
[115, 114, 93]
[3, 5, 58]
[38, 37, 63]
[94, 96, 33]
[57, 96, 54]
[98, 1, 99]
[17, 61, 58]
[4, 74, 60]
[53, 96, 54]
[55, 50, 88]
[98, 60, 95]
[95, 59, 98]
[55, 97, 18]
[27, 10, 19]
[38, 37, 51]
[116, 39, 68]
[47, 48, 14]
[30, 28, 79]
[104, 97, 14]
[86, 85, 45]
[87, 36, 108]
[110, 91, 36]
[74, 72, 60]
[17, 83, 74]
[108, 87, 75]
[56, 95, 71]
[41, 73, 39]
[41, 42, 73]
[43, 44